import { expect, test, type Page } from "@playwright/test";
import { sendBirthDocumentsDepositEmailForReservation, type BirthDocumentsDepositEmailTransport } from "../../src/features/communications/birth-documents-deposit-email-core";
import { runBirthDocumentsDepositCampaign } from "../../src/features/reservations/birth-documents-deposit-campaign";
import { getBrevoTransactionalTemplateConfig } from "../../src/features/settings/brevo-template-registry";
import { createAuthenticatedSupabaseClient, E2E_OWNER_EMAIL, E2E_OWNER_PASSWORD, runE2eSqlSync } from "./helpers/supabase";

const org = "20000000-0000-4000-8000-000000000001"; const owner = "10000000-0000-4000-8000-000000000001";
const ids = { group: "97000000-0000-4000-8000-000000000001", litter: "97000000-0000-4000-8000-000000000002", template: "97000000-0000-4000-8000-000000000003", contact: "97000000-0000-4000-8000-000000000004", app: "97000000-0000-4000-8000-000000000005", reservation: "97000000-0000-4000-8000-000000000006", paid: "97000000-0000-4000-8000-000000000007", active: "97000000-0000-4000-8000-000000000008" };
const q = (v: string) => `'${v.replaceAll("'", "''")}'`;
const sql = (value: string) => runE2eSqlSync(value);

function cleanup() {
  sql(`delete from public.email_delivery_attempts where litter_id=${q(ids.litter)}::uuid;
    delete from public.payments where reservation_id=${q(ids.reservation)}::uuid;
    delete from public.reservations where id=${q(ids.reservation)}::uuid;
    delete from public.applications where id=${q(ids.app)}::uuid;
    delete from public.contacts where id=${q(ids.contact)}::uuid;
    delete from public.email_templates where id=${q(ids.template)}::uuid;
    delete from public.litters where id=${q(ids.litter)}::uuid;
    delete from public.litter_groups where id=${q(ids.group)}::uuid;`);
}
function remaining() { return Number(sql(`select count(*) from (select id from public.email_delivery_attempts where litter_id=${q(ids.litter)}::uuid union all select id from public.payments where reservation_id=${q(ids.reservation)}::uuid union all select id from public.reservations where id=${q(ids.reservation)}::uuid union all select id from public.applications where id=${q(ids.app)}::uuid union all select id from public.contacts where id=${q(ids.contact)}::uuid union all select id from public.email_templates where id=${q(ids.template)}::uuid union all select id from public.litters where id=${q(ids.litter)}::uuid union all select id from public.litter_groups where id=${q(ids.group)}::uuid) x;`)); }
function fixture({ active = false, email = "camille.birth@example.invalid" } = {}) {
  cleanup(); sql(`insert into public.litter_groups(id,organization_id,name,species,status,created_by,updated_by) values(${q(ids.group)},${q(org)},'E2E naissance groupe','dog','born',${q(owner)},${q(owner)});
    insert into public.litters(id,organization_id,litter_group_id,name,species,breed,status,actual_birth_date,created_by,updated_by) values(${q(ids.litter)},${q(org)},${q(ids.group)},'E2E naissance portée','dog','Golden Retriever','born','2026-07-10',${q(owner)},${q(owner)});
    insert into public.contacts(id,organization_id,contact_type,first_name,last_name,display_name,email,origin_channel,primary_status,created_by,updated_by) values(${q(ids.contact)},${q(org)},'person','Camille','Naissance','Camille Naissance',${email ? q(email) : "null"},'manual','active',${q(owner)},${q(owner)});
    insert into public.applications(id,organization_id,contact_id,species,breed,desired_litter_id,desired_litter_group_id,desired_sex_preference,desired_quantity,status,created_by,updated_by) values(${q(ids.app)},${q(org)},${q(ids.contact)},'dog','Golden Retriever',${q(ids.litter)},${q(ids.group)},'female_preferred_male_possible',1,'qualified',${q(owner)},${q(owner)});
    insert into public.reservations(id,organization_id,application_id,contact_id,litter_id,litter_group_id,species,breed,reserved_sex_preference,status,currency,created_by,updated_by) values(${q(ids.reservation)},${q(org)},${q(ids.app)},${q(ids.contact)},${q(ids.litter)},${q(ids.group)},'dog','Golden Retriever','female_preferred_male_possible','pre_reservation_paid','EUR',${q(owner)},${q(owner)});
    insert into public.payments(id,organization_id,contact_id,reservation_id,amount_cents,currency,payment_type,status,paid_at,payment_method,notes,created_by,updated_by) values(${q(ids.paid)},${q(org)},${q(ids.contact)},${q(ids.reservation)},25000,'EUR','pre_reservation_deposit_refundable','paid',now(),'bank_transfer','Demande 1/2 réglée',${q(owner)},${q(owner)});
    insert into public.email_templates(id,organization_id,template_key,title,category,subject,body,is_active,brevo_template_id,created_by,updated_by) values(${q(ids.template)},${q(org)},'birth_documents_deposit','Contrat + certificat et complément d’arrhes','adopter_journey','Registre technique','Registre technique',true,765432,${q(owner)},${q(owner)});
    ${active ? `insert into public.payments(id,organization_id,contact_id,reservation_id,amount_cents,currency,payment_type,status,payment_method,due_date,notes,created_by,updated_by) values(${q(ids.active)},${q(org)},${q(ids.contact)},${q(ids.reservation)},25000,'EUR','arrhes','requested','bank_transfer','2026-07-27','Demande 2/2 — complément d’arrhes',${q(owner)},${q(owner)});` : ""}`);
}
function transport(mode: "success" | "failed" | "unconfigured" = "success") {
  const sends: unknown[] = []; const value: BirthDocumentsDepositEmailTransport = { isConfigured: () => mode !== "unconfigured", getTemplate: async (id) => ({ ok: true, template: { id, name: "QA", subject: "Sujet Brevo QA", isActive: true, modifiedAt: "2026-07-12T10:00:00Z", sender: null, replyTo: null } }), sendEmail: async (input) => { sends.push(input); return mode === "failed" ? { ok: false, reason: "invalid_request" } : { ok: true, messageId: "qa-birth-1" }; } }; return { value, sends };
}
async function login(page: Page) { await page.goto("/login"); await page.getByLabel("Email").fill(E2E_OWNER_EMAIL); await page.getByLabel("Mot de passe").fill(E2E_OWNER_PASSWORD); await page.getByRole("button", { name: "Se connecter" }).click(); await expect(page).toHaveURL(/\/candidatures/); }

test("registry, settings and adopter journey expose birth_documents_deposit", async ({ page }) => { fixture(); try { expect(getBrevoTransactionalTemplateConfig("birth_documents_deposit")).toMatchObject({ category: "adopter_journey" }); await login(page); await page.goto("/settings/organization#brevo-templates"); await expect(page.getByText("birth_documents_deposit", { exact: true })).toBeVisible(); await page.goto(`/litters/${ids.litter}`); await page.getByText("Campagnes d’e-mails").click(); await expect(page.getByText("Contrat + certificat", { exact: true })).toBeVisible(); await expect(page.getByRole("button", { name: "Préparer le complément et envoyer via Brevo" })).toBeVisible(); } finally { cleanup(); expect(remaining()).toBe(0); } });

test("250 euros paid creates 250 euros complement and sends only once", async () => { fixture(); const supabase = await createAuthenticatedSupabaseClient(); const t = transport(); try { const first = await runBirthDocumentsDepositCampaign({ supabase, litterId: ids.litter, reservationIds: [ids.reservation], userId: owner, sendEmail: (input) => sendBirthDocumentsDepositEmailForReservation(input, { supabase, transport: t.value }) }); expect(first).toMatchObject({ status: "success", paymentsCreatedCount: 1, emailsSentCount: 1 }); const second = await runBirthDocumentsDepositCampaign({ supabase, litterId: ids.litter, reservationIds: [ids.reservation], userId: owner, sendEmail: (input) => sendBirthDocumentsDepositEmailForReservation(input, { supabase, transport: t.value }) }); expect(second).toMatchObject({ emailsAlreadySentCount: 1, paymentsCreatedCount: 0, paymentsReusedCount: 1 }); expect(t.sends).toHaveLength(1); expect(t.sends[0]).toMatchObject({ params: { montant_deja_regle: "250,00 €", montant_complement_arrhes: "250,00 €", arrhes_totales: "500,00 €", date_naissance: "10 juillet 2026" } }); expect(Number(sql(`select amount_cents from public.payments where reservation_id=${q(ids.reservation)} and status='requested' and deleted_at is null;`))).toBe(25000); } finally { cleanup(); expect(remaining()).toBe(0); } });

test("existing request is reused; certain failure compensates only a new request; uncertainty retains it", async () => { const supabase = await createAuthenticatedSupabaseClient(); fixture({ active: true }); try { const reused = await runBirthDocumentsDepositCampaign({ supabase, litterId: ids.litter, reservationIds: [ids.reservation], userId: owner, sendEmail: async () => ({ status: "success", deliveryState: "sent" }) }); expect(reused).toMatchObject({ paymentsReusedCount: 1, paymentsCreatedCount: 0 }); cleanup(); fixture(); const failed = await runBirthDocumentsDepositCampaign({ supabase, litterId: ids.litter, reservationIds: [ids.reservation], userId: owner, sendEmail: async () => ({ status: "failed", deliveryState: "not_sent" }) }); expect(failed).toMatchObject({ paymentsCreatedCount: 1, compensatedCount: 1 }); expect(Number(sql(`select count(*) from public.payments where reservation_id=${q(ids.reservation)} and status='requested' and deleted_at is null;`))).toBe(0); cleanup(); fixture(); const uncertain = await runBirthDocumentsDepositCampaign({ supabase, litterId: ids.litter, reservationIds: [ids.reservation], userId: owner, sendEmail: async () => ({ status: "failed", deliveryState: "uncertain" }) }); expect(uncertain).toMatchObject({ paymentsCreatedCount: 1, uncertainCount: 1, compensatedCount: 0 }); expect(Number(sql(`select count(*) from public.payments where reservation_id=${q(ids.reservation)} and status='requested' and deleted_at is null;`))).toBe(1); } finally { cleanup(); expect(remaining()).toBe(0); } });

test("complete, unpaid, missing email, missing model and unconfigured Brevo create no lasting request or email", async () => { const supabase = await createAuthenticatedSupabaseClient(); fixture(); try { sql(`update public.payments set amount_cents=50000 where id=${q(ids.paid)};`); let result = await runBirthDocumentsDepositCampaign({ supabase, litterId: ids.litter, reservationIds: [ids.reservation], userId: owner, sendEmail: async () => ({ status: "success", deliveryState: "sent" }) }); expect(result.completeCount).toBe(1); sql(`update public.payments set amount_cents=10000 where id=${q(ids.paid)};`); result = await runBirthDocumentsDepositCampaign({ supabase, litterId: ids.litter, reservationIds: [ids.reservation], userId: owner, sendEmail: async () => ({ status: "success", deliveryState: "sent" }) }); expect(result.preReservationUnpaidCount).toBe(1); cleanup(); fixture({ email: "" }); result = await runBirthDocumentsDepositCampaign({ supabase, litterId: ids.litter, reservationIds: [ids.reservation], userId: owner, sendEmail: (input) => sendBirthDocumentsDepositEmailForReservation(input, { supabase, transport: transport().value }) }); expect(result).toMatchObject({ emailsMissingCount: 1, compensatedCount: 1 }); cleanup(); fixture(); sql(`delete from public.email_templates where id=${q(ids.template)};`); result = await runBirthDocumentsDepositCampaign({ supabase, litterId: ids.litter, reservationIds: [ids.reservation], userId: owner, sendEmail: (input) => sendBirthDocumentsDepositEmailForReservation(input, { supabase, transport: transport().value }) }); expect(result).toMatchObject({ missingTemplateCount: 1, compensatedCount: 1 }); cleanup(); fixture(); result = await runBirthDocumentsDepositCampaign({ supabase, litterId: ids.litter, reservationIds: [ids.reservation], userId: owner, sendEmail: (input) => sendBirthDocumentsDepositEmailForReservation(input, { supabase, transport: transport("unconfigured").value }) }); expect(result).toMatchObject({ brevoNotConfiguredCount: 1, compensatedCount: 1 }); expect(Number(sql(`select count(*) from public.documents where reservation_id=${q(ids.reservation)};`))).toBe(0); } finally { cleanup(); expect(remaining()).toBe(0); } });
