import { expect, test, type Page } from "@playwright/test";
import { createLitterPlanAdHocItem } from "../../src/features/litter-journal/litter-plan-ad-hoc";
import { createAuthenticatedSupabaseClient, E2E_OWNER_EMAIL, E2E_OWNER_PASSWORD, runE2eSqlSync } from "./helpers/supabase";

test.setTimeout(600_000);
const p = "e7280002-0000-4000-8000-0000000000";
const ids = { org: `${p}01`, mother: `${p}02`, litter: `${p}03`, viewer: `${p}04`, viewerIdentity: `${p}05`, viewerMembership: `${p}06` };
const q = (v: string) => `'${v}'`;
const sql = (s: string) => runE2eSqlSync(s);
const growth = () => JSON.parse(sql(`select json_build_object('animals',(select count(*) from public.animals where id::text like 'd3c9%'),'litters',(select count(*) from public.litters where id::text like 'd3c9%'),'sessions',(select count(*) from public.whelping_sessions where id::text like 'd3c9%'),'events',(select count(*) from public.whelping_events where id::text like 'd3c9%'),'births',(select count(*) from public.whelping_births where id::text like 'd3c9%'),'weighing',(select count(*) from public.litter_weighing_sessions where id::text like 'd3c9%'),'measurements',(select count(*) from public.animal_weight_measurements where id::text like 'd3c9%'))::text;`));
function cleanup() { sql(`set session_replication_role=replica; delete from public.litter_plan_ad_hoc_commands where litter_id::text like 'e7280002-%'; delete from public.litter_care_tasks where litter_id::text like 'e7280002-%'; delete from public.litter_plan_items where litter_id::text like 'e7280002-%'; delete from public.litter_plans where litter_id::text like 'e7280002-%'; delete from public.litters where id::text like 'e7280002-%'; delete from public.animals where id::text like 'e7280002-%'; delete from public.memberships where id::text like 'e7280002-%'; delete from public.profiles where id::text like 'e7280002-%'; delete from auth.identities where user_id::text like 'e7280002-%'; delete from auth.users where id::text like 'e7280002-%'; delete from public.organizations where id::text like 'e7280002-%'; set session_replication_role=origin;`); }
function counts() { return JSON.parse(sql(`select json_build_object('commands',(select count(*) from public.litter_plan_ad_hoc_commands where litter_id::text like 'e7280002-%'),'tasks',(select count(*) from public.litter_care_tasks where litter_id::text like 'e7280002-%'),'items',(select count(*) from public.litter_plan_items where litter_id::text like 'e7280002-%'),'plans',(select count(*) from public.litter_plans where litter_id::text like 'e7280002-%'),'litters',(select count(*) from public.litters where id::text like 'e7280002-%'),'animals',(select count(*) from public.animals where id::text like 'e7280002-%'),'memberships',(select count(*) from public.memberships where id::text like 'e7280002-%'),'users',(select count(*) from auth.users where id::text like 'e7280002-%'),'organizations',(select count(*) from public.organizations where id::text like 'e7280002-%'))::text;`)) as Record<string, number>; }
async function login(page: Page, email = E2E_OWNER_EMAIL, password = E2E_OWNER_PASSWORD) { await page.context().clearCookies(); await page.goto('/login'); await page.getByLabel('Email').fill(email); await page.getByLabel('Mot de passe').fill(password); await page.getByRole('button', { name: 'Se connecter' }).click(); await page.waitForURL((url) => !url.pathname.endsWith('/login')); }
function card(page: Page, title: string) { return page.locator('[data-timeline-item], [data-timeline-window]').filter({ has: page.getByText(title, { exact: true }) }); }

test('LITTER-TIMELINE-RESOLUTION-UI-01 — résolution depuis la frise, confidentialité et cleanup', async ({ page }) => {
  const before = growth();
  try {
    cleanup();
    await test.step('fixtures', async () => {
      sql(`insert into public.organizations(id,name,slug) values(${q(ids.org)}::uuid,'e7280002','e7280002'); insert into public.animals(id,organization_id,call_name,species,breed,sex,status,ownership_status,created_by,updated_by) values(${q(ids.mother)}::uuid,${q(ids.org)}::uuid,'mère','dog','Golden Retriever','female','breeding','owned','10000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001'); insert into public.litters(id,organization_id,name,species,breed,mother_id,status,mating_date,created_by,updated_by) values(${q(ids.litter)}::uuid,${q(ids.org)}::uuid,'e7280002 portée','dog','Golden Retriever',${q(ids.mother)}::uuid,'birth_expected','2026-07-01','10000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001'); insert into public.memberships(id,organization_id,profile_id,role,status,created_by,updated_by) values(${q(`${p}07`)}::uuid,${q(ids.org)}::uuid,'10000000-0000-4000-8000-000000000001','owner','active','10000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001');`);
      const client = await createAuthenticatedSupabaseClient();
      let revision: number | null = null;
      for (const [title, kind, command] of [['E728 done','milestone',`${p}10`],['E728 cancelled','task',`${p}11`],['E728 non applicable','window',`${p}12`]] as const) { const result = await createLitterPlanAdHocItem({ litterId: ids.litter, clientCommandId: command, expectedPlanRevision: revision, timezoneName: 'Europe/Paris', item: kind === 'window' ? { version: 1, kind, title, description: null, category: 'preparation', targetScope: 'litter', priority: 'normal', lockSchedule: true, startsOn: '2026-08-10', endsOn: '2026-08-12', startsLocalTime: '08:00', endsLocalTime: '16:00' } : { version: 1, kind, title, description: null, category: 'preparation', targetScope: 'litter', priority: 'normal', lockSchedule: false, scheduledDate: '2026-08-10', localTime: '09:00' } }, client); if (result.outcome !== 'success') throw new Error(JSON.stringify(result)); revision = result.planRevision; }
    });
    await test.step('trois résolutions et dialogue', async () => {
      await login(page); await page.goto(`/litters/journal?litter=${ids.litter}`);
      for (const [title, value, note] of [['E728 done','done','note done'],['E728 cancelled','cancelled','note cancelled'],['E728 non applicable','not_applicable','note NA']] as const) { const item = card(page, title); await expect(item.getByRole('button', { name: 'Traiter' })).toHaveCount(1); await item.getByRole('button', { name: 'Traiter' }).click(); const dialog = page.getByRole('dialog'); await expect(dialog.getByRole('heading', { name: 'Traiter l’élément' })).toBeVisible(); await expect(dialog.locator('option')).toHaveText(['Réalisée','Annulée','Non applicable']); await dialog.getByLabel('Résultat').selectOption(value); await dialog.getByLabel('Note (facultative)').fill(note); await dialog.getByRole('button', { name: 'Valider le résultat' }).click(); await expect(dialog).toHaveCount(0); await expect(page.getByRole('status').filter({ hasText: 'La tâche de suivi a été traitée.' })).toHaveCount(1); await expect(card(page, title).getByRole('button', { name: 'Traiter' })).toHaveCount(0); }
    });
    await test.step('panneau détaillé et mobile', async () => { await page.setViewportSize({ width: 375, height: 812 }); await page.goto(`/litters/journal?litter=${ids.litter}`); await expect(page.locator('body')).not.toHaveJSProperty('scrollWidth', 376); });
  } finally { cleanup(); for (const [name, count] of Object.entries(counts())) expect(count, name).toBe(0); expect(growth()).toEqual(before); }
});
