import { createHash, randomUUID } from "node:crypto";
import { writeFileSync } from "node:fs";
import { createClient as createSupabaseClient } from "@supabase/supabase-js";

import { expect, test } from "@playwright/test";

import { createTestAdopterFinalizationReadyScenario, registerActualFinalizationEffects } from "./helpers/fixtures/adopter-finalization-fixtures";
import { withE2eFixtures } from "./helpers/fixtures/fixture-registry";
import { registerPostAdoptionQuestionnaireEffects } from "./helpers/fixtures/post-adoption-questionnaire-fixtures";
import { E2E_OWNER_EMAIL, E2E_OWNER_PASSWORD, createAuthenticatedSupabaseClient, runE2eSql, runE2eSqlSync } from "./helpers/supabase";

const sql = (statement: string) => runE2eSqlSync(statement);
const q = (value: string) => `'${value.replaceAll("'", "''")}'`;
const organizationId = "20000000-0000-4000-8000-000000000001";
const ownerId = "10000000-0000-4000-8000-000000000001";
test.use({ deviceScaleFactor: 2 });

test("authorizes and finalizes only a fully prepared owner-admin departure", async ({ page }) => {
  test.setTimeout(120_000);
  await withE2eFixtures(runE2eSql, async (fixtures) => {
    const supabase = await createAuthenticatedSupabaseClient();
    const scenario = await createTestAdopterFinalizationReadyScenario(runE2eSql, fixtures, { organizationId, ownerId, displayName: `E2E départ final ${fixtures.namespace}`, animalCallName: `E2E chiot départ ${fixtures.namespace}`, birthDate: "2026-06-01" });
    const planId=randomUUID(),linkId=randomUUID(),slotId=randomUUID(),paymentId=randomUUID(),saleId=randomUUID(),signedReturnId=randomUUID(),contractId=randomUUID(),commitmentId=randomUUID(); let signatureEventId: string | null = null;
    const fakeHash="a".repeat(64); const signedBytes=Buffer.from("%PDF-1.4\n1 0 obj<</Type/Catalog>>endobj\ntrailer<</Root 1 0 R>>\n%%EOF"); const signedPdfHash=createHash("sha256").update(signedBytes).digest("hex"); const path=`organizations/${organizationId}/documents/${saleId}/signed-returns/${signedReturnId}/${signedPdfHash}.pdf`;
    sql(`
      update public.animals set identification_number='250269000000099' where id=${q(scenario.animal.id)};
      update public.reservations set price_cents=200000 where id=${q(scenario.journey.id)};
      insert into public.departure_plans(id,organization_id,status,title,default_duration_minutes,response_deadline_at,published_at,published_by,created_by,updated_by) values(${q(planId)},${q(organizationId)},'published','E2E départ',75,'2026-09-01',now(),${q(ownerId)},${q(ownerId)},${q(ownerId)});
      insert into public.departure_plan_litters(id,organization_id,plan_id,litter_id,earliest_departure_at,created_by) values(${q(linkId)},${q(organizationId)},${q(planId)},${q(scenario.litterId)},'2026-08-01',${q(ownerId)});
      insert into public.departure_slots(id,organization_id,plan_id,starts_at,duration_minutes,visibility,status,reservation_id,booked_at,booked_by_kind,confirmed_at,created_by,updated_by) values(${q(slotId)},${q(organizationId)},${q(planId)},'2026-08-17T10:00:00Z',75,'exceptional','booked',${q(scenario.journey.id)},now(),'exceptional',now(),${q(ownerId)},${q(ownerId)});
      insert into public.payments(id,organization_id,contact_id,reservation_id,amount_cents,payment_type,status,payment_method,paid_at,created_by,updated_by) values(${q(paymentId)},${q(organizationId)},${q(scenario.contact.id)},${q(scenario.journey.id)},150000,'balance','paid','bank_transfer',now(),${q(ownerId)},${q(ownerId)});
      insert into public.documents(id,organization_id,contact_id,reservation_id,litter_id,animal_id,document_type,status,title,signature_required,sent_at,signed_at,file_path,file_name,mime_type,file_size_bytes,file_sha256,created_by,updated_by) values
      (${q(commitmentId)},${q(organizationId)},${q(scenario.contact.id)},${q(scenario.journey.id)},${q(scenario.litterId)},null,'commitment_certificate','signed','CEC signé',true,now(),now(),null,null,null,null,null,${q(ownerId)},${q(ownerId)}),
      (${q(contractId)},${q(organizationId)},${q(scenario.contact.id)},${q(scenario.journey.id)},${q(scenario.litterId)},null,'reservation_contract','signed','Contrat signé',true,now(),now(),null,null,null,null,null,${q(ownerId)},${q(ownerId)}),
      (${q(saleId)},${q(organizationId)},${q(scenario.contact.id)},${q(scenario.journey.id)},${q(scenario.litterId)},${q(scenario.animal.id)},'sale_certificate','generated','Attestation à signer',true,null,null,'organizations/${organizationId}/documents/${saleId}/v1/${fakeHash}.pdf','attestation.pdf','application/pdf',100,${q(fakeHash)},${q(ownerId)},${q(ownerId)});
    `);
    fixtures.register("departure_plans",planId);fixtures.register("departure_plan_litters",linkId);fixtures.register("departure_slots",slotId);fixtures.register("payments",paymentId);[commitmentId,contractId,saleId].forEach((id)=>fixtures.register("documents",id));
    await page.goto("/login"); await page.getByLabel("Email").fill(E2E_OWNER_EMAIL); await page.getByLabel("Mot de passe").fill(E2E_OWNER_PASSWORD); await page.getByRole("button", { name: "Se connecter" }).click(); await expect(page).toHaveURL(/\/candidatures/); await page.goto(`/reservations/${scenario.journey.id}/depart`); await expect(page.getByRole("heading", { name: "Signature de la famille sur iPad" })).toBeVisible(); await page.screenshot({ path: "/tmp/departure-finalization-desktop-2x.png", fullPage: true }); await page.setViewportSize({ width: 390, height: 844 }); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390); await page.screenshot({ path: "/tmp/departure-finalization-mobile-2x.png", fullPage: true });
    const service = createSupabaseClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false, autoRefreshToken: false } }); const upload=await service.storage.from("documents").upload(path,signedBytes,{contentType:"application/pdf",upsert:false}); expect(upload.error).toBeNull(); const consentText="Consentement E2E vérifié par la famille"; const consentHash=createHash("sha256").update(consentText).digest("hex"); try { const signature=await service.rpc("archive_sale_certificate_signature_service",{p_actor_profile_id:ownerId,p_document_id:saleId,p_signed_return_id:signedReturnId,p_file_path:path,p_file_sha256:signedPdfHash,p_file_size_bytes:signedBytes.byteLength,p_source_pdf_sha256:fakeHash,p_signature_sha256:createHash("sha256").update("signature-e2e").digest("hex"),p_signer_name:"Famille E2E",p_consent_text:consentText,p_consent_sha256:consentHash,p_client_command_id:randomUUID()}); fixtures.register("document_signed_returns",signedReturnId); signatureEventId=sql(`select coalesce((select id::text from public.departure_signature_events where signed_return_id=${q(signedReturnId)}),'')`); if(signatureEventId)fixtures.register("departure_signature_events",signatureEventId); expect(signature.error).toBeNull(); expect(signature.data?.[0]?.outcome).toBe("created"); } finally { const removed=await service.storage.from("documents").remove([path]); expect(removed.error).toBeNull(); }
    const updatedAt=sql(`select updated_at::text from public.reservations where id=${q(scenario.journey.id)}`);const adoptionAt="2026-08-17T10:30:00.000Z";
    const balanceCommand = randomUUID(); const balanceResult = await (supabase as unknown as {rpc:(name:string,args:Record<string,unknown>)=>Promise<{data:Array<{outcome:string;payment_id:string;amount_cents:number}>|null;error:unknown}>}).rpc("record_departure_final_balance", { p_reservation_id: scenario.journey.id, p_payment_method: "card", p_reference: "E2E-SOLDE", p_expected_reservation_updated_at: updatedAt, p_client_command_id: balanceCommand }); if (balanceResult.data?.[0]?.payment_id) fixtures.register("payments", balanceResult.data[0].payment_id); const balanceCommandRow=sql(`select id from public.departure_commands where client_command_id=${q(balanceCommand)}`); if(balanceCommandRow)fixtures.register("departure_commands",balanceCommandRow); expect(balanceResult.error).toBeNull(); expect(balanceResult.data?.[0]).toMatchObject({ outcome: "recorded", amount_cents: 50000 }); const balanceReplay = await (supabase as unknown as {rpc:(name:string,args:Record<string,unknown>)=>Promise<{data:Array<{outcome:string;payment_id:string;amount_cents:number}>|null;error:unknown}>}).rpc("record_departure_final_balance", { p_reservation_id: scenario.journey.id, p_payment_method: "card", p_reference: "E2E-SOLDE", p_expected_reservation_updated_at: updatedAt, p_client_command_id: balanceCommand }); expect(balanceReplay.data?.[0]?.outcome).toBe("existing"); expect(sql(`select count(*)::text from public.payments where reservation_id=${q(scenario.journey.id)} and amount_cents=50000`)).toBe("1");
    const command=randomUUID();const finalized=await (supabase as unknown as {rpc:(name:string,args:Record<string,unknown>)=>Promise<{data:Array<{outcome:string;event_id:string}>|null;error:unknown}>}).rpc("finalize_departure_adoption_handover",{p_reservation_id:scenario.journey.id,p_client_command_id:command,p_adoption_completed_at:adoptionAt,p_expected_reservation_updated_at:updatedAt,p_physical_documents_handed_over:true,p_acknowledged_exception_codes:[],p_exception_reason:null});if(finalized.data?.[0]?.event_id)fixtures.register("adoption_handover_events",finalized.data[0].event_id);expect(finalized.error).toBeNull();expect(finalized.data?.[0]?.outcome).toBe("success");
    const correction = await (supabase as unknown as {rpc:(name:string,args:Record<string,unknown>)=>Promise<{data:Array<{outcome:string;event_id:string}>|null;error:unknown}>}).rpc("correct_adoption_handover", { p_reservation_id: scenario.journey.id, p_client_command_id: randomUUID(), p_correction_type: "reverse", p_expected_adoption_completed_at: adoptionAt, p_new_adoption_completed_at: null, p_reason: "Correction E2E avant suivi" }); if (correction.data?.[0]?.event_id) fixtures.register("adoption_handover_events", correction.data[0].event_id); expect(correction.error).toBeNull(); expect(correction.data?.[0]?.outcome).toBe("success"); expect(sql(`select status from public.departure_slots where id=${q(slotId)}`)).toBe("booked");
    const refreshedUpdatedAt = sql(`select updated_at::text from public.reservations where id=${q(scenario.journey.id)}`); const refinalized = await (supabase as unknown as {rpc:(name:string,args:Record<string,unknown>)=>Promise<{data:Array<{outcome:string;event_id:string}>|null;error:unknown}>}).rpc("finalize_departure_adoption_handover", { p_reservation_id: scenario.journey.id, p_client_command_id: randomUUID(), p_adoption_completed_at: adoptionAt, p_expected_reservation_updated_at: refreshedUpdatedAt, p_physical_documents_handed_over: true, p_acknowledged_exception_codes: [], p_exception_reason: null }); if (refinalized.data?.[0]?.event_id) fixtures.register("adoption_handover_events", refinalized.data[0].event_id); expect(refinalized.error).toBeNull(); expect(refinalized.data?.[0]?.outcome).toBe("success");
    await registerActualFinalizationEffects(runE2eSql,fixtures,{organizationId,reservationId:scenario.journey.id,contactId:scenario.contact.id,animalId:scenario.animal.id});await registerPostAdoptionQuestionnaireEffects(runE2eSql,fixtures,{reservationIds:[scenario.journey.id]});
    expect(sql(`select status from public.reservations where id=${q(scenario.journey.id)}`)).toBe("adopted");expect(sql(`select status from public.departure_slots where id=${q(slotId)}`)).toBe("completed");expect(sql(`select count(*)::text from public.post_adoption_questionnaire_instances where reservation_id=${q(scenario.journey.id)}`)).toBe("2");
    if (process.env.E2E_FIXTURE_REPORT_PATH) {
      const generated = JSON.parse(sql(`select json_build_object('adoptionEvents',coalesce((select json_agg(id order by occurred_at) from public.adoption_handover_events where reservation_id=${q(scenario.journey.id)}),'[]'::json),'questionnaireInstances',coalesce((select json_agg(id order by created_at) from public.post_adoption_questionnaire_instances where reservation_id=${q(scenario.journey.id)}),'[]'::json),'contactRoles',coalesce((select json_agg(id order by created_at) from public.contact_roles where contact_id=${q(scenario.contact.id)}),'[]'::json))::text`));
      writeFileSync(`${process.env.E2E_FIXTURE_REPORT_PATH}-finalization.json`, JSON.stringify({ namespace: fixtures.namespace, contactId: scenario.contact.id, reservationId: scenario.journey.id, litterId: scenario.litterId, animalId: scenario.animal.id, planId, linkId, slotId, paymentId, documentIds: [commitmentId, contractId, saleId], signedReturnId, signatureEventId, generated }, null, 2));
    }
  });
});
