import { createHash, randomUUID } from "node:crypto";
import { writeFileSync } from "node:fs";

import { expect, test } from "@playwright/test";

import { withE2eFixtures } from "./helpers/fixtures/fixture-registry";
import { E2E_OWNER_EMAIL, E2E_OWNER_PASSWORD, createAuthenticatedSupabaseClient, runE2eSqlSync } from "./helpers/supabase";

const sql = (statement: string) => runE2eSqlSync(statement);
const q = (value: string) => `'${value.replaceAll("'", "''")}'`;
const organizationId = "20000000-0000-4000-8000-000000000001";
const ownerId = "10000000-0000-4000-8000-000000000001";
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
test.use({ deviceScaleFactor: 2 });

test("publishes enough blocks and gives the last public block to one family only", async ({ page }) => {
  test.setTimeout(120_000);
  await withE2eFixtures(sql, async (fixtures) => {
    const supabase = await createAuthenticatedSupabaseClient();
    const litterId = randomUUID(); const contactIds = [randomUUID(), randomUUID()]; const animalIds = [randomUUID(), randomUUID()]; const reservationIds = [randomUUID(), randomUUID()];
    sql(`
      insert into public.litters(id,organization_id,name,species,breed,status,actual_birth_date,created_by,updated_by) values(${q(litterId)},${q(organizationId)},'E2E départ ${fixtures.namespace}','dog','Golden Retriever','ready_to_leave','2026-07-01',${q(ownerId)},${q(ownerId)});
      insert into public.contacts(id,organization_id,contact_type,display_name,email,origin_channel,primary_status,created_by,updated_by) values
      (${q(contactIds[0]!)},${q(organizationId)},'person','E2E départ famille A','depart-a@example.invalid','manual','active',${q(ownerId)},${q(ownerId)}),
      (${q(contactIds[1]!)},${q(organizationId)},'person','E2E départ famille B','depart-b@example.invalid','manual','active',${q(ownerId)},${q(ownerId)});
      insert into public.animals(id,organization_id,litter_id,species,breed,sex,call_name,status,ownership_status,identification_number,created_by,updated_by) values
      (${q(animalIds[0]!)},${q(organizationId)},${q(litterId)},'dog','Golden Retriever','female','E2E départ A','reserved','produced','250269000000011',${q(ownerId)},${q(ownerId)}),
      (${q(animalIds[1]!)},${q(organizationId)},${q(litterId)},'dog','Golden Retriever','male','E2E départ B','reserved','produced','250269000000012',${q(ownerId)},${q(ownerId)});
      insert into public.reservations(id,organization_id,contact_id,litter_id,animal_id,species,breed,status,animal_assigned_at,price_cents,created_by,updated_by) values
      (${q(reservationIds[0]!)},${q(organizationId)},${q(contactIds[0]!)},${q(litterId)},${q(animalIds[0]!)},'dog','Golden Retriever','animal_assigned',now(),100000,${q(ownerId)},${q(ownerId)}),
      (${q(reservationIds[1]!)},${q(organizationId)},${q(contactIds[1]!)},${q(litterId)},${q(animalIds[1]!)},'dog','Golden Retriever','animal_assigned',now(),100000,${q(ownerId)},${q(ownerId)});
    `);
    fixtures.register("litters", litterId); contactIds.forEach((id) => fixtures.register("contacts", id)); animalIds.forEach((id) => fixtures.register("animals", id)); reservationIds.forEach((id) => fixtures.register("reservations", id));
    const planCommand = randomUUID();
    const plan = await (supabase as unknown as { rpc: (name: string,args:Record<string,unknown>) => Promise<{data:Array<{outcome:string;plan_id:string;version:number}>|null;error:unknown}> }).rpc("create_departure_plan", { p_title:"E2E week-end",p_default_duration_minutes:75,p_litters:[{litterId,earliestDepartureAt:"2026-08-26T00:00:00.000Z"}],p_client_command_id:planCommand });
    const planId = plan.data?.[0]?.plan_id; if (planId) fixtures.register("departure_plans", planId); expect(plan.error).toBeNull(); expect(plan.data?.[0]?.outcome).toBe("created"); if (!planId) throw new Error("departure plan id missing");
    const planEffects=JSON.parse(sql(`select json_build_object('link',(select id from public.departure_plan_litters where plan_id=${q(planId)}),'command',(select id from public.departure_commands where client_command_id=${q(planCommand)}),'event',(select id from public.departure_events where client_command_id=${q(planCommand)}))::text`)) as {link:string;command:string;event:string}; fixtures.register("departure_plan_litters",planEffects.link);fixtures.register("departure_commands",planEffects.command);fixtures.register("departure_events",planEffects.event);
    let version=1; const slotIds:string[]=[]; const slotCommandIds:string[]=[];
    for(const [index,start] of ["2026-09-04T08:00:00.000Z","2026-09-04T09:15:00.000Z"].entries()){
      const command=randomUUID(); slotCommandIds.push(command); const duration=index===0?75:180; const result=await (supabase as unknown as {rpc:(name:string,args:Record<string,unknown>)=>Promise<{data:Array<{outcome:string;slot_id:string;version:number}>|null;error:unknown}>}).rpc("upsert_departure_slot",{p_plan_id:planId,p_slot_id:null,p_starts_at:start,p_duration_minutes:duration,p_visibility:"public",p_reservation_id:null,p_expected_version:version,p_client_command_id:command});const createdSlotId=result.data?.[0]?.slot_id;if(createdSlotId)fixtures.register("departure_slots",createdSlotId);expect(result.data?.[0]?.outcome,`slot ${index}`).toBe("updated");if(!createdSlotId)throw new Error("departure slot id missing");slotIds.push(createdSlotId);version=result.data![0]!.version;const effects=JSON.parse(sql(`select json_build_object('command',(select id from public.departure_commands where client_command_id=${q(command)}),'event',(select id from public.departure_events where client_command_id=${q(command)}))::text`)) as {command:string;event:string};fixtures.register("departure_commands",effects.command);fixtures.register("departure_events",effects.event);
    }
    const secondPlanCommand=randomUUID(); const secondPlan=await (supabase as unknown as {rpc:(name:string,args:Record<string,unknown>)=>Promise<{data:Array<{outcome:string;plan_id:string}>|null;error:unknown}>}).rpc("create_departure_plan",{p_title:"E2E chevauchement",p_default_duration_minutes:75,p_litters:[{litterId,earliestDepartureAt:"2026-08-26T00:00:00.000Z"}],p_client_command_id:secondPlanCommand}); const secondPlanId=secondPlan.data?.[0]?.plan_id; if(secondPlanId)fixtures.register("departure_plans",secondPlanId); expect(secondPlan.error).toBeNull(); if(!secondPlanId)throw new Error("second departure plan id missing"); const overlap=await (supabase as unknown as {rpc:(name:string,args:Record<string,unknown>)=>Promise<{data:unknown;error:{code?:string}|null}>}).rpc("upsert_departure_slot",{p_plan_id:secondPlanId,p_slot_id:null,p_starts_at:"2026-09-04T08:30:00.000Z",p_duration_minutes:75,p_visibility:"public",p_reservation_id:null,p_expected_version:1,p_client_command_id:randomUUID()}); expect(overlap.error?.code).toBe("23P01");
    await page.goto("/login");await page.getByLabel("Email").fill(E2E_OWNER_EMAIL);await page.getByLabel("Mot de passe").fill(E2E_OWNER_PASSWORD);await page.getByRole("button",{name:"Se connecter"}).click();await expect(page).toHaveURL(/\/candidatures/,{timeout:30_000});await page.goto(`/departs?plan=${planId}&week=2026-08-31`);await expect(page.getByRole("heading",{name:"E2E week-end"})).toBeVisible();
    const shortBlock=page.locator(`[data-departure-slot="${slotIds[0]}"]`);const longBlock=page.locator(`[data-departure-slot="${slotIds[1]}"]`);await expect(shortBlock).toHaveAttribute("data-duration-minutes","75");await expect(longBlock).toHaveAttribute("data-duration-minutes","180");expect((await shortBlock.boundingBox())?.height).toBeCloseTo(80,0);expect((await longBlock.boundingBox())?.height).toBeCloseTo(192,0);await expect(page.locator("[data-resize-handle]")).toHaveCount(2);
    const dragHandle=shortBlock.locator("[data-drag-handle]");await dragHandle.hover();const targetBox=await page.locator('[data-departure-drop-day="2026-09-04"][data-departure-drop-hour="16"]').boundingBox();if(!targetBox)throw new Error("drag geometry missing");await page.mouse.down();await expect(shortBlock).toHaveAttribute("data-dragging","true");await page.mouse.move(targetBox.x+targetBox.width/2,targetBox.y+targetBox.height/2,{steps:8});await page.mouse.up();await expect.poll(()=>sql(`select to_char(starts_at at time zone 'Europe/Paris','YYYY-MM-DD HH24:MI') from public.departure_slots where id=${q(slotIds[0]!)}`)).toBe("2026-09-04 16:00");await expect(page.getByRole("region",{name:"Agenda hebdomadaire des départs"})).toHaveAttribute("data-plan-version","4");
    const resizeHandle=page.locator(`[data-departure-slot="${slotIds[1]}"] [data-resize-handle]`);await resizeHandle.hover();const handleBox=await resizeHandle.boundingBox();if(!handleBox)throw new Error("resize handle missing");await page.mouse.down();await expect(longBlock).toHaveAttribute("data-resizing","true");await page.mouse.move(handleBox.x+handleBox.width/2,handleBox.y+handleBox.height/2+16);await page.mouse.up();await expect.poll(()=>sql(`select duration_minutes::text from public.departure_slots where id=${q(slotIds[1]!)}`)).toBe("195");version=Number(sql(`select version::text from public.departure_plans where id=${q(planId)}`));
    const publishCommand=randomUUID();const published=await (supabase as unknown as {rpc:(name:string,args:Record<string,unknown>)=>Promise<{data:Array<{outcome:string;version:number}>|null;error:unknown}>}).rpc("publish_departure_plan",{p_plan_id:planId,p_response_deadline_at:"2026-09-01T18:00:00.000Z",p_expected_version:version,p_client_command_id:publishCommand});expect(published.data?.[0]?.outcome).toBe("published");const publishEffects=JSON.parse(sql(`select json_build_object('command',(select id from public.departure_commands where client_command_id=${q(publishCommand)}),'event',(select id from public.departure_events where client_command_id=${q(publishCommand)}))::text`)) as {command:string;event:string};fixtures.register("departure_commands",publishEffects.command);fixtures.register("departure_events",publishEffects.event);
    await page.goto(`/departs?plan=${planId}`);await expect(page.getByRole("heading",{name:"Agenda des rendez-vous de départ"})).toBeVisible();await expect(page.getByRole("heading",{name:"E2E week-end"})).toBeVisible();await expect.poll(() => page.locator("[data-departure-calendar-scroll]").evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);await page.screenshot({path:"/tmp/departure-planning-desktop-2x.png",fullPage:true});await page.setViewportSize({width:390,height:844});await expect(page.getByRole("heading",{name:"Agenda des rendez-vous de départ"})).toBeVisible();await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.screenshot({path:"/tmp/departure-planning-mobile-2x.png",fullPage:true});
    const accessIds=[randomUUID(),randomUUID()];const sessionIds=[randomUUID(),randomUUID()];const sessionTokens=["session-a","session-b"];
    sql(`insert into public.departure_public_accesses(id,organization_id,plan_id,reservation_id,token_hash,token_hint,expires_at) values(${q(accessIds[0]!)},${q(organizationId)},${q(planId)},${q(reservationIds[0]!)},${q(hash("token-a"))},'token-a1','2026-10-01'),(${q(accessIds[1]!)},${q(organizationId)},${q(planId)},${q(reservationIds[1]!)},${q(hash("token-b"))},'token-b1','2026-10-01');insert into public.departure_public_sessions(id,organization_id,access_id,session_hash,expires_at) values(${q(sessionIds[0]!)},${q(organizationId)},${q(accessIds[0]!)},${q(hash(sessionTokens[0]!))},now()+interval '2 hours'),(${q(sessionIds[1]!)},${q(organizationId)},${q(accessIds[1]!)},${q(hash(sessionTokens[1]!))},now()+interval '2 hours');`);accessIds.forEach((id)=>fixtures.register("departure_public_accesses",id));sessionIds.forEach((id)=>fixtures.register("departure_public_sessions",id));
    const firstCommand=randomUUID();const first=JSON.parse(sql(`select row_to_json(result)::text from public.book_departure_public_session(${q(hash(sessionTokens[0]!))},${q(slotIds[0]!)},${q(firstCommand)}) result`));expect(first.outcome).toBe("booked");
    await page.setViewportSize({width:1440,height:900});await page.goto(`/departs?plan=${planId}&week=2026-08-31`);const bookedBlock=page.locator(`[data-departure-slot="${slotIds[0]}"]`);await bookedBlock.locator("[data-resize-handle]").press("ArrowDown");await expect.poll(()=>sql(`select duration_minutes::text from public.departure_slots where id=${q(slotIds[0]!)}`)).toBe("90");expect(JSON.parse(sql(`select details::text from public.departure_events where slot_id=${q(slotIds[0]!)} and event_type='appointment_duration_changed' order by occurred_at desc limit 1`))).toMatchObject({previousDurationMinutes:75,durationMinutes:90});
    const crossSessionReplay=JSON.parse(sql(`select row_to_json(result)::text from public.book_departure_public_session(${q(hash(sessionTokens[1]!))},${q(slotIds[0]!)},${q(firstCommand)}) result`));expect(crossSessionReplay).toMatchObject({outcome:"unavailable",reason:"slot_unavailable"});
    const secondCommand=randomUUID();const second=JSON.parse(sql(`select row_to_json(result)::text from public.book_departure_public_session(${q(hash(sessionTokens[1]!))},${q(slotIds[0]!)},${q(secondCommand)}) result`));expect(second).toMatchObject({outcome:"unavailable",reason:"slot_unavailable"});
    for(const command of [firstCommand]){const effects=JSON.parse(sql(`select json_build_object('command',(select id from public.departure_commands where client_command_id=${q(command)}),'event',(select id from public.departure_events where client_command_id=${q(command)}),'calendar',(select id from public.events where departure_slot_id=${q(slotIds[0]!)}) )::text`)) as {command:string;event:string;calendar:string};fixtures.register("departure_commands",effects.command);fixtures.register("departure_events",effects.event);fixtures.register("events",effects.calendar);}
    expect(sql(`select count(*)::text from public.departure_slots where id=${q(slotIds[0]!)} and reservation_id=${q(reservationIds[0]!)}`)).toBe("1");expect(sql(`select count(*)::text from public.departure_slots where id=${q(slotIds[0]!)} and reservation_id=${q(reservationIds[1]!)}`)).toBe("0");
    if (process.env.E2E_FIXTURE_REPORT_PATH) {
      const commandIds = [planCommand, ...slotCommandIds, publishCommand, firstCommand];
      const generated = JSON.parse(sql(`select json_build_object('commands',coalesce((select json_agg(id order by created_at) from public.departure_commands where client_command_id in (${commandIds.map(q).join(",")})),'[]'::json),'events',coalesce((select json_agg(id order by occurred_at) from public.departure_events where plan_id=${q(planId)}),'[]'::json),'calendarEvents',coalesce((select json_agg(id order by created_at) from public.events where departure_slot_id in (${slotIds.map(q).join(",")})),'[]'::json))::text`));
      writeFileSync(`${process.env.E2E_FIXTURE_REPORT_PATH}-planning.json`, JSON.stringify({ namespace: fixtures.namespace, litterId, contactIds, animalIds, reservationIds, planId, slotIds, accessIds, sessionIds, generated }, null, 2));
    }
  });
  expect(JSON.parse(sql(`select json_build_object('contacts',(select count(*) from public.contacts where display_name like 'E2E départ%'),'animals',(select count(*) from public.animals where call_name like 'E2E départ%'),'litters',(select count(*) from public.litters where name like 'E2E départ%'),'plans',(select count(*) from public.departure_plans where title in ('E2E week-end','E2E chevauchement')))::text`))).toEqual({contacts:0,animals:0,litters:0,plans:0});
});
