import type { SupabaseClient } from "@supabase/supabase-js";

import type { Database } from "@/types/database.types";

type Supabase = SupabaseClient<Database>;
type PlanningDb = SupabaseClient<Record<string, never>>;
type Role = "owner" | "admin" | "member" | "viewer";
type RawRow = Record<string, unknown>;
type RawRpc = (name: string, args: Record<string, unknown>) => Promise<{ data: RawRow[] | null; error: unknown }>;

export const LITTER_PLANNING_MODEL_ITEM_KINDS = ["milestone", "task", "window"] as const;
export const LITTER_PLANNING_MODEL_PRIORITIES = ["normal", "important", "organization_critical"] as const;
export const LITTER_PLANNING_MODEL_ANCHORS = ["first_mating", "estimated_ovulation", "expected_birth", "actual_birth", "offspring_age"] as const;
export type LitterPlanningModelItemKind = (typeof LITTER_PLANNING_MODEL_ITEM_KINDS)[number];
export type LitterPlanningModelPriority = (typeof LITTER_PLANNING_MODEL_PRIORITIES)[number];
export type LitterPlanningModelAnchor = (typeof LITTER_PLANNING_MODEL_ANCHORS)[number];
export type LitterPlanningModelItemInput = { organizationTemplateId: string; itemKind: LitterPlanningModelItemKind; priority: LitterPlanningModelPriority; anchorType: LitterPlanningModelAnchor; pointOffsetDays?: number; pointLocalTime?: string | null; windowStartsOffsetDays?: number; windowStartsLocalTime?: string | null; windowEndsOffsetDays?: number; windowEndsLocalTime?: string | null; displayOrder: number; isRequired: boolean; isSelectedByDefault: boolean };
export type LitterPlanningModelInput = { title: string; description?: string | null; species?: "dog" | "cat" | null; breed?: string | null; isActive?: boolean; items: LitterPlanningModelItemInput[] };
export type LitterPlanningModelItem = LitterPlanningModelItemInput & { id: string };
export type LitterPlanningModel = { id: string; title: string; description: string | null; species: "dog" | "cat" | null; breed: string | null; isActive: boolean; revision: number; items: LitterPlanningModelItem[] };
export type LitterPlanningModelErrorCode = "invalid_input" | "unauthenticated" | "forbidden" | "not_found" | "conflict" | "stale_revision" | "database_error";
export type LitterPlanningModelResult = { outcome: "success"; modelId: string; revision: number; isActive: boolean; replayed: boolean } | { outcome: "error"; error: { code: LitterPlanningModelErrorCode; message: string } };

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const TIME = /^([01]\d|2[0-3]):[0-5]\d(?::[0-5]\d)?$/;
const db = (supabase: Supabase) => supabase as unknown as PlanningDb;
const rpc = (supabase: Supabase, name: string, args: Record<string, unknown>) => (db(supabase).rpc as unknown as RawRpc)(name, args);
const failure = (code: LitterPlanningModelErrorCode, message: string): LitterPlanningModelResult => ({ outcome: "error", error: { code, message } });
const uuid = (value: unknown) => typeof value === "string" && UUID.test(value.trim()) ? value.trim().toLowerCase() : null;
const text = (value: unknown, limit: number, required = false) => { if (value == null || value === "") return required ? null : null; if (typeof value !== "string") return undefined; const normalized = value.trim(); return (!required || normalized) && normalized.length <= limit ? (normalized || null) : undefined; };
const integer = (value: unknown) => typeof value === "number" && Number.isInteger(value) ? value : null;
const time = (value: unknown) => value == null || value === "" ? null : typeof value === "string" && TIME.test(value.trim()) ? value.trim() : undefined;

function normalizeItems(value: unknown): LitterPlanningModelItemInput[] | null {
  if (!Array.isArray(value) || value.length > 100) return null;
  const orders = new Set<number>();
  const items: LitterPlanningModelItemInput[] = [];
  for (const raw of value) {
    if (!raw || typeof raw !== "object") return null;
    const item = raw as Record<string, unknown>; const organizationTemplateId = uuid(item.organizationTemplateId); const displayOrder = integer(item.displayOrder);
    const pointOffsetDays = item.pointOffsetDays === undefined ? undefined : integer(item.pointOffsetDays); const start = item.windowStartsOffsetDays === undefined ? undefined : integer(item.windowStartsOffsetDays); const end = item.windowEndsOffsetDays === undefined ? undefined : integer(item.windowEndsOffsetDays);
    const pointLocalTime = time(item.pointLocalTime); const windowStartsLocalTime = time(item.windowStartsLocalTime); const windowEndsLocalTime = time(item.windowEndsLocalTime);
    if (!organizationTemplateId || displayOrder === null || displayOrder < 0 || orders.has(displayOrder) || !LITTER_PLANNING_MODEL_ITEM_KINDS.includes(item.itemKind as LitterPlanningModelItemKind) || !LITTER_PLANNING_MODEL_PRIORITIES.includes(item.priority as LitterPlanningModelPriority) || !LITTER_PLANNING_MODEL_ANCHORS.includes(item.anchorType as LitterPlanningModelAnchor) || typeof item.isRequired !== "boolean" || typeof item.isSelectedByDefault !== "boolean" || pointLocalTime === undefined || windowStartsLocalTime === undefined || windowEndsLocalTime === undefined) return null;
    if (item.isRequired && !item.isSelectedByDefault) return null;
    if (item.itemKind === "window") { if (pointOffsetDays !== undefined || pointLocalTime !== null || start === undefined || end === undefined || start > end || (start === end && windowStartsLocalTime && windowEndsLocalTime && windowStartsLocalTime > windowEndsLocalTime)) return null; }
    else if (pointOffsetDays === undefined || start !== undefined || end !== undefined || windowStartsLocalTime !== null || windowEndsLocalTime !== null) return null;
    orders.add(displayOrder); items.push({ organizationTemplateId, itemKind: item.itemKind as LitterPlanningModelItemKind, priority: item.priority as LitterPlanningModelPriority, anchorType: item.anchorType as LitterPlanningModelAnchor, pointOffsetDays, pointLocalTime, windowStartsOffsetDays: start, windowStartsLocalTime, windowEndsOffsetDays: end, windowEndsLocalTime, displayOrder, isRequired: item.isRequired, isSelectedByDefault: item.isSelectedByDefault });
  } return items;
}

function normalizeModel(input: LitterPlanningModelInput) { const title = text(input.title, 255, true); const description = text(input.description, 5000); const breed = text(input.breed, 255); const items = normalizeItems(input.items); return title && description !== undefined && breed !== undefined && items && (input.species == null || input.species === "dog" || input.species === "cat") && (input.isActive === undefined || typeof input.isActive === "boolean") ? { title, description, breed, species: input.species ?? null, isActive: input.isActive ?? true, items } : null; }
function mapMutation(row: RawRow | undefined): LitterPlanningModelResult { const modelId = uuid(row?.model_id); if (row?.outcome !== "success" || !modelId || !Number.isInteger(row.revision) || typeof row.revision !== "number" || row.revision <= 0 || typeof row.is_active !== "boolean") { const code = row?.reason === "stale_revision" ? "stale_revision" : row?.reason === "client_command_conflict" ? "conflict" : row?.reason === "membership_required" ? "forbidden" : row?.reason === "not_authenticated" ? "unauthenticated" : row?.reason === "model_not_found" ? "not_found" : "invalid_input"; return failure(code, "La modification du modèle n’a pas pu être effectuée."); } return { outcome: "success", modelId, revision: row.revision, isActive: row.is_active, replayed: row.replayed === true }; }

export async function listLitterPlanningModelsCore(organizationId: string, supabase: Supabase): Promise<{ outcome: "success"; role: Role; models: Omit<LitterPlanningModel, "items">[] } | LitterPlanningModelResult> { const org = uuid(organizationId); if (!org) return failure("invalid_input", "La demande est invalide."); const membership = await supabase.from("memberships").select("role").eq("organization_id", org).eq("profile_id", (await supabase.auth.getUser()).data.user?.id ?? "").eq("status", "active").is("deleted_at", null).maybeSingle(); if (membership.error) return failure("database_error", "La lecture des modèles est indisponible."); if (!membership.data) return failure("not_found", "Le modèle est introuvable."); const result = await db(supabase).from("litter_planning_models").select("id,title,description,species,breed,is_active,revision").eq("organization_id", org).order("is_active", { ascending: false }).order("title"); if (result.error) return failure("database_error", "La lecture des modèles est indisponible."); return { outcome: "success", role: membership.data.role as Role, models: ((result.data ?? []) as RawRow[]).map((row) => ({ id: row.id as string, title: row.title as string, description: row.description as string | null, species: row.species as "dog" | "cat" | null, breed: row.breed as string | null, isActive: row.is_active as boolean, revision: row.revision as number })) }; }
export async function getLitterPlanningModelCore(modelId: string, supabase: Supabase): Promise<{ outcome: "success"; role: Role; model: LitterPlanningModel } | LitterPlanningModelResult> { const id = uuid(modelId); if (!id) return failure("invalid_input", "La demande est invalide."); const model = await db(supabase).from("litter_planning_models").select("*").eq("id", id).maybeSingle(); if (model.error) return failure("database_error", "La lecture du modèle est indisponible."); if (!model.data) return failure("not_found", "Le modèle est introuvable."); const rawModel = model.data as RawRow; const organizationId = rawModel.organization_id as string; const auth = await listLitterPlanningModelsCore(organizationId, supabase); if (auth.outcome === "error") return auth; const items = await db(supabase).from("litter_planning_model_items").select("*").eq("organization_id", organizationId).eq("model_id", id).order("display_order"); if (items.error) return failure("database_error", "La lecture du modèle est indisponible."); return { outcome: "success", role: auth.role, model: { id: rawModel.id as string, title: rawModel.title as string, description: rawModel.description as string | null, species: rawModel.species as "dog" | "cat" | null, breed: rawModel.breed as string | null, isActive: rawModel.is_active as boolean, revision: rawModel.revision as number, items: ((items.data ?? []) as RawRow[]).map((row) => ({ id: row.id as string, organizationTemplateId: row.organization_template_id as string, itemKind: row.item_kind as LitterPlanningModelItemKind, priority: row.priority as LitterPlanningModelPriority, anchorType: row.anchor_type as LitterPlanningModelAnchor, pointOffsetDays: row.point_offset_days as number | undefined, pointLocalTime: row.point_local_time as string | null, windowStartsOffsetDays: row.window_starts_offset_days as number | undefined, windowStartsLocalTime: row.window_starts_local_time as string | null, windowEndsOffsetDays: row.window_ends_offset_days as number | undefined, windowEndsLocalTime: row.window_ends_local_time as string | null, displayOrder: row.display_order as number, isRequired: row.is_required as boolean, isSelectedByDefault: row.is_selected_by_default as boolean })) } }; }
export async function createLitterPlanningModelCore(organizationId: string, clientCommandId: string, input: LitterPlanningModelInput, supabase: Supabase) { const org = uuid(organizationId), command = uuid(clientCommandId), model = normalizeModel(input); if (!org || !command || !model) return failure("invalid_input", "La demande est invalide."); const result = await rpc(supabase, "create_litter_planning_model", { p_organization_id: org, p_client_command_id: command, p_title: model.title, p_description: model.description, p_species: model.species, p_breed: model.breed, p_is_active: model.isActive, p_items: model.items }); return result.error ? failure("database_error", "La modification du modèle n’a pas pu être effectuée.") : mapMutation(result.data?.[0]); }
export async function replaceLitterPlanningModelCore(modelId: string, clientCommandId: string, expectedRevision: number, input: LitterPlanningModelInput, supabase: Supabase) { const id = uuid(modelId), command = uuid(clientCommandId), model = normalizeModel(input); if (!id || !command || !Number.isInteger(expectedRevision) || expectedRevision <= 0 || !model) return failure("invalid_input", "La demande est invalide."); const result = await rpc(supabase, "replace_litter_planning_model", { p_model_id: id, p_client_command_id: command, p_expected_revision: expectedRevision, p_title: model.title, p_description: model.description, p_species: model.species, p_breed: model.breed, p_items: model.items }); return result.error ? failure("database_error", "La modification du modèle n’a pas pu être effectuée.") : mapMutation(result.data?.[0]); }
export async function setLitterPlanningModelActiveCore(modelId: string, clientCommandId: string, expectedRevision: number, isActive: boolean, supabase: Supabase) { const id = uuid(modelId), command = uuid(clientCommandId); if (!id || !command || !Number.isInteger(expectedRevision) || expectedRevision <= 0 || typeof isActive !== "boolean") return failure("invalid_input", "La demande est invalide."); const result = await rpc(supabase, "set_litter_planning_model_active", { p_model_id: id, p_client_command_id: command, p_expected_revision: expectedRevision, p_is_active: isActive }); return result.error ? failure("database_error", "La modification du modèle n’a pas pu être effectuée.") : mapMutation(result.data?.[0]); }
