"use client";

import { useActionState, useEffect, useId, useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { litterCareTaskCategoryLabels, litterCareTaskTargetLabels } from "./litter-care-task-labels";
import { LITTER_CARE_TASK_CATEGORIES, LITTER_CARE_TASK_PRIORITIES, LITTER_CARE_TASK_TARGET_SCOPES } from "./litter-care-tasks-core";
import type { LitterPlanAdHocMetadataActionState } from "./litter-plan-ad-hoc-metadata-actions";

type Action = (previous: LitterPlanAdHocMetadataActionState, data: FormData) => Promise<LitterPlanAdHocMetadataActionState>;
export type LitterPlanAdHocMetadataView = { title: string; description: string | null; category: string; targetScope: string; priority: string; kind: "milestone" | "task" | "window" };
const initial: LitterPlanAdHocMetadataActionState = { status: "idle" };
const kindLabel = (kind: LitterPlanAdHocMetadataView["kind"]) => kind === "milestone" ? "Jalon" : kind === "window" ? "Période" : "Tâche";

export function LitterPlanAdHocMetadataDialog({ view, action, onSuccess }: { view: LitterPlanAdHocMetadataView; action: Action; onSuccess: (message: string) => void }) {
  const [open, setOpen] = useState(false); const [state, submit] = useActionState(action, initial); const id = useId().replace(/:/g, "");
  useEffect(() => { if (state.status === "success") queueMicrotask(() => { setOpen(false); onSuccess(state.message ?? "Informations mises à jour."); }); }, [state, onSuccess]);
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button type="button" size="sm" variant="outline">Modifier les informations</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-lg"><DialogHeader><DialogTitle>Modifier les informations</DialogTitle><DialogDescription>Le calendrier, le verrouillage et le statut restent inchangés.</DialogDescription></DialogHeader><form action={submit} className="space-y-4"><p className="text-sm"><span className="font-semibold">Type :</span> {kindLabel(view.kind)}</p><label className="block text-sm font-semibold" htmlFor={`${id}-title`}>Titre<input id={`${id}-title`} name="title" defaultValue={view.title} maxLength={255} required className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm font-semibold" htmlFor={`${id}-description`}>Description<textarea id={`${id}-description`} name="description" defaultValue={view.description ?? ""} maxLength={5000} className="mt-1 min-h-20 w-full rounded border p-2" /></label><label className="block text-sm font-semibold" htmlFor={`${id}-category`}>Catégorie<select id={`${id}-category`} name="category" defaultValue={view.category} className="mt-1 w-full rounded border p-2">{LITTER_CARE_TASK_CATEGORIES.map((value) => <option key={value} value={value}>{litterCareTaskCategoryLabels[value]}</option>)}</select></label><label className="block text-sm font-semibold" htmlFor={`${id}-target`}>Cible<select id={`${id}-target`} name="target_scope" defaultValue={view.targetScope} className="mt-1 w-full rounded border p-2">{LITTER_CARE_TASK_TARGET_SCOPES.map((value) => <option key={value} value={value}>{litterCareTaskTargetLabels[value]}</option>)}</select></label><label className="block text-sm font-semibold" htmlFor={`${id}-priority`}>Priorité<select id={`${id}-priority`} name="priority" defaultValue={view.priority} className="mt-1 w-full rounded border p-2">{LITTER_CARE_TASK_PRIORITIES.map((value) => <option key={value} value={value}>{value === "normal" ? "Normale" : value === "important" ? "Importante" : "Critique pour l’organisation"}</option>)}</select></label>{state.status === "error" ? <p className="text-sm text-destructive" role="alert">{state.message}</p> : null}<DialogFooter><Button type="submit" disabled={state.requiresRefresh}>{state.requiresRefresh ? "Rechargez le Journal" : "Enregistrer"}</Button></DialogFooter></form></DialogContent></Dialog>;
}
