import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { randomUUID } from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";

import { generateSaleCertificateAction, markDepartureStatusAction, recordDepartureBalanceAction, sendDepartureDocumentsAction, signSaleCertificateAction } from "@/features/departures/departure-finalization-actions";
import { DepartureSignaturePad } from "@/features/departures/departure-signature-pad";
import { DEPARTURE_SIGNATURE_CONSENT_TEXT } from "@/features/departures/departure-signature-consent";
import { isoToParisLocalInput } from "@/features/departures/departure-time-zone";
import { adoptReservation } from "@/features/reservations/actions";
import { createClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";
const money = (cents: number) => new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" }).format(cents / 100);
const localNow = () => isoToParisLocalInput(new Date().toISOString());

export default async function DepartureFinalizationPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string,string|undefined>> }) {
  const { id } = await params; const query = await searchParams; const supabase = await createClient();
  const returnTo = query.return_to?.startsWith("/reservations?") && !query.return_to.includes("//") ? query.return_to : `/reservations?view=current&selected=${id}`; const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const reservation = await supabase.from("reservation_overview").select("id,organization_id,contact_id,contact_display_name,animal_id,animal_display_name,litter_id,price_cents,paid_cents,refunded_cents,currency,status,updated_at").eq("id", id).maybeSingle();
  if (reservation.error || !reservation.data) notFound(); const row = reservation.data;
  const membership = await supabase.from("memberships").select("role").eq("organization_id", row.organization_id!).eq("profile_id", user.id).eq("status", "active").is("deleted_at", null).maybeSingle();
  if (!membership.data || !["owner","admin"].includes(membership.data.role)) redirect(`/reservations/${id}`);
  const loose = supabase as unknown as SupabaseClient;
  const [animalResult, slotResult, documentResult, incidentResult, optionalDocumentsResult, legacyDocumentsResult] = await Promise.all([
    loose.from("animals").select("id,call_name,official_name,birth_date,identification_number,status,ownership_status").eq("id", row.animal_id).maybeSingle(),
    loose.from("departure_slots").select("id,starts_at,duration_minutes,status,confirmed_at").eq("organization_id", row.organization_id).eq("reservation_id", id).in("status", ["booked","late","to_review"]).order("booked_at", { ascending: false }).limit(1).maybeSingle(),
    loose.from("documents").select("id,status,file_sha256,animal_id,generation_data,document_signed_returns(id)").eq("organization_id", row.organization_id).eq("reservation_id", id).eq("animal_id", row.animal_id).eq("document_type", "sale_certificate").is("deleted_at", null).is("superseded_at", null).order("created_at", { ascending: false }).limit(1).maybeSingle(),
    row.litter_id ? loose.from("post_birth_incidents").select("id,summary").eq("organization_id", row.organization_id).eq("litter_id", row.litter_id).eq("status", "open") : Promise.resolve({ data: [], error: null }),
    loose.from("documents").select("id,animal_id,title,document_type,status,file_path").eq("organization_id", row.organization_id).eq("reservation_id", id).in("document_type", ["invoice","veterinary_certificate","birth_certificate"]).is("deleted_at", null),
    loose.from("documents").select("document_type,status").eq("organization_id", row.organization_id).eq("reservation_id", id).in("document_type", ["commitment_certificate","reservation_contract"]).is("deleted_at", null).is("superseded_at", null),
  ]);
  const animal = animalResult.data as { id: string; call_name: string | null; official_name: string | null; birth_date: string | null; identification_number: string | null; status: string; ownership_status: string } | null;
  const slot = slotResult.data as { id: string; starts_at: string; duration_minutes: number; status: string; confirmed_at: string | null } | null;
  const saleCertificate = documentResult.data as { id: string; status: string; file_sha256: string | null; animal_id: string | null; generation_data: unknown; document_signed_returns: Array<{ id: string }> | null } | null;
  const optionalDocuments = ((optionalDocumentsResult.data ?? []) as Array<{ id: string; animal_id: string | null; title: string; document_type: string; status: string; file_path: string | null }>).filter((document) => Boolean(document.file_path) && (document.document_type === "invoice" ? document.animal_id === null || document.animal_id === row.animal_id : document.animal_id === row.animal_id));
  const legacyDocuments = (legacyDocumentsResult.data ?? []) as Array<{ document_type: string; status: string }>;
  const commitmentDocument = legacyDocuments.find((document) => document.document_type === "commitment_certificate");
  const reservationContractDocument = legacyDocuments.find((document) => document.document_type === "reservation_contract");
  const legacyExceptions = [
    !commitmentDocument ? "commitment_certificate_missing" : commitmentDocument.status === "signed" ? null : "commitment_certificate_not_signed",
    !reservationContractDocument ? "reservation_contract_missing" : reservationContractDocument.status === "signed" ? null : "reservation_contract_not_signed",
  ].filter((value): value is string => Boolean(value));
  const paid = Number(row.paid_cents ?? 0) - Number(row.refunded_cents ?? 0); const balance = row.price_cents === null ? null : row.price_cents - paid;
  const identificationReady = Boolean(animal?.identification_number?.trim()); const appointmentReady = Boolean(slot?.confirmed_at && ["booked","late"].includes(slot.status)); const certificateGenerated = Boolean(saleCertificate?.id && saleCertificate.animal_id === row.animal_id); const certificateSigned = saleCertificate?.status === "signed" && Boolean(saleCertificate.document_signed_returns?.length); const incidentOpen = (incidentResult.data ?? []).length > 0;
  const ready = row.status === "animal_assigned" && identificationReady && appointmentReady && balance === 0 && certificateSigned && !incidentOpen;
  const statuses = [query.document_status && `Attestation : ${query.document_status}`, query.signature_status && `Signature : ${query.signature_status}`, query.payment_status && `Paiement : ${query.payment_status}`, query.documents_email_status && `Email des documents : ${query.documents_email_status}`].filter(Boolean);

  return <main className="mx-auto min-h-screen w-full max-w-5xl px-4 py-8 sm:px-8"><Link href={returnTo} className="text-sm font-semibold text-accent hover:underline">← Retour au parcours adoptant</Link><header className="mt-5 border-b pb-6"><p className="text-sm font-semibold uppercase tracking-wide text-accent">Contrôle final du départ</p><h1 className="mt-2 text-3xl font-semibold">{row.contact_display_name ?? "Famille"} · {row.animal_display_name ?? animal?.call_name ?? "Chiot"}</h1><p className="mt-3 text-sm text-muted">Les informations déjà présentes sont relues automatiquement. Complétez seulement le paiement éventuel, la signature et la remise physique.</p></header>{statuses.length ? <p role="status" className="mt-5 rounded-xl border bg-surface p-4 text-sm font-semibold">{statuses.join(" · ")}</p> : null}
  <section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
    ["Rendez-vous", appointmentReady, slot ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Paris" }).format(new Date(slot.starts_at)) : "Non confirmé"],
    ["Identification", identificationReady, animal?.identification_number ?? "Manquante"],
    ["Attestation", certificateSigned, certificateSigned ? "Signée et archivée" : certificateGenerated ? "Prête à signer" : "À générer"],
    ["Paiement final", balance === 0, balance === null ? "Prix manquant" : balance === 0 ? "Dossier soldé" : balance > 0 ? `${money(balance)} restant` : `Trop-perçu de ${money(Math.abs(balance))} à résoudre`],
  ].map(([label,ok,detail]) => <article key={String(label)} className={`rounded-xl border p-4 ${ok ? "border-emerald-200 bg-emerald-50" : "border-amber-200 bg-amber-50"}`}><p className="text-xs font-semibold uppercase text-muted">{String(label)}</p><p className="mt-1 font-semibold">{String(detail)}</p></article>)}</section>
  {slot ? <section className="mt-5 rounded-xl border bg-surface p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-muted">Situation du rendez-vous</p><p className="mt-1 font-semibold">{slot.status.replaceAll("_", " ")}</p></div><div className="flex flex-wrap gap-2">{[["late","En retard"],["no_show","Absent"]] .map(([status,label]) => <form key={status} action={markDepartureStatusAction}><input type="hidden" name="client_command_id" value={randomUUID()} /><input type="hidden" name="reservation_id" value={id} /><input type="hidden" name="return_to" value={returnTo} /><input type="hidden" name="slot_id" value={slot.id} /><input type="hidden" name="status" value={status} /><input type="hidden" name="reason" value={status === "no_show" ? "Famille absente au rendez-vous" : "Famille en retard"} /><button className="rounded-lg border px-3 py-2 text-xs font-semibold">{label}</button></form>)}</div></div></section> : null}
  {incidentOpen ? <div role="alert" className="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-950">Un incident sensible est encore ouvert. Le rendez-vous reste visible, mais la finalisation est bloquée.</div> : null}
  {!identificationReady ? <p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm">Renseignez d’abord l’identification sur la <Link href={`/animals/${row.animal_id}#identite-definitive`} className="font-semibold text-accent">fiche Animal</Link>.</p> : null}
  {identificationReady && !certificateGenerated ? <section className="mt-5 rounded-2xl border bg-surface p-5"><h2 className="text-xl font-semibold">Attestation de vente</h2><p className="mt-2 text-sm text-muted">Le PDF reprendra la famille, le chiot attribué, son identification et le prix convenu.</p><form action={generateSaleCertificateAction} className="mt-4"><input type="hidden" name="reservation_id" value={id} /><input type="hidden" name="return_to" value={returnTo} /><button className="rounded-xl bg-accent px-4 py-2.5 text-sm font-semibold text-white">Générer l’attestation</button></form></section> : null}
  {saleCertificate && !certificateSigned ? <section className="mt-5 rounded-2xl border bg-surface p-5 sm:p-6"><h2 className="text-xl font-semibold">Signature de la famille sur iPad</h2><p className="mt-2 text-sm text-muted">La signature sera intégrée au PDF exact puis archivée. Aucune pièce d’identité n’est enregistrée.</p><Link href={`/documents/${saleCertificate.id}/pdf`} target="_blank" className="mt-3 inline-flex text-sm font-semibold text-accent underline">Afficher l’attestation exacte à signer</Link><form action={signSaleCertificateAction} className="mt-5 space-y-4"><input type="hidden" name="reservation_id" value={id} /><input type="hidden" name="return_to" value={returnTo} /><input type="hidden" name="document_id" value={saleCertificate.id} /><input type="hidden" name="client_command_id" value={randomUUID()} /><label className="block text-sm font-semibold">Nom affiché<input name="signer_name" required defaultValue={row.contact_display_name ?? ""} className="mt-2 w-full rounded-xl border px-3 py-2" /></label><DepartureSignaturePad /><label className="flex gap-3 rounded-xl border bg-background p-4 text-sm"><input required type="checkbox" name="consent_confirmed" value="yes" /><span>{DEPARTURE_SIGNATURE_CONSENT_TEXT}</span></label><button className="w-full rounded-xl bg-accent px-4 py-3 font-semibold text-white">Signer et archiver le PDF</button></form></section> : null}
  {balance !== null && balance > 0 ? <section className="mt-5 rounded-2xl border bg-surface p-5"><h2 className="text-xl font-semibold">Paiement final reçu sur place</h2><form action={recordDepartureBalanceAction} className="mt-4 grid gap-3 sm:grid-cols-[160px_180px_1fr_auto] sm:items-end"><input type="hidden" name="reservation_id" value={id} /><input type="hidden" name="return_to" value={returnTo} /><input type="hidden" name="client_command_id" value={randomUUID()} /><input type="hidden" name="expected_reservation_updated_at" value={row.updated_at ?? ""} /><div><p className="text-xs font-semibold uppercase text-muted">Montant prérempli</p><p className="mt-2 text-lg font-semibold">{money(balance)}</p></div><label className="text-xs font-semibold uppercase text-muted">Moyen<select name="payment_method" className="mt-1 w-full rounded-lg border px-3 py-2 text-sm normal-case"><option value="bank_transfer">Virement</option><option value="cash">Espèces</option><option value="card">Carte</option><option value="cheque">Chèque</option><option value="other">Autre</option></select></label><label className="text-xs font-semibold uppercase text-muted">Référence facultative<input name="reference" className="mt-1 w-full rounded-lg border px-3 py-2 text-sm normal-case" /></label><button className="rounded-lg bg-accent px-4 py-2 text-sm font-semibold text-white">Enregistrer</button></form></section> : null}
  <section className="mt-5 rounded-2xl border bg-surface p-5"><h2 className="text-xl font-semibold">Documents à transmettre</h2><p className="mt-2 text-sm text-muted">L’attestation signée est obligatoire. Les autres PDF disponibles sont précochés et peuvent être retirés.</p><form action={sendDepartureDocumentsAction} className="mt-4 space-y-2"><input type="hidden" name="reservation_id" value={id} /><input type="hidden" name="return_to" value={returnTo} />{saleCertificate ? <label className="flex items-center gap-3 rounded-lg border bg-background p-3 text-sm font-semibold"><input type="checkbox" name="document_ids" value={saleCertificate.id} checked readOnly />Attestation de vente signée · obligatoire</label> : null}{optionalDocuments.map((document) => <label key={document.id} className="flex items-center gap-3 rounded-lg border bg-background p-3 text-sm"><input type="checkbox" name="document_ids" value={document.id} defaultChecked />{document.title} · {document.status}</label>)}<button disabled={!certificateSigned} className="mt-3 rounded-xl bg-accent px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Relire et envoyer via Brevo</button></form><p className="mt-3 text-xs text-muted">Une panne d’envoi ne bloque pas la finalisation ; la tentative restera à reprendre.</p></section>
  <section className="mt-5 rounded-2xl border-2 border-accent/30 bg-accent-soft p-5"><h2 className="text-xl font-semibold">Finaliser l’adoption</h2><p className="mt-2 text-sm text-muted">La date et l’heure actuelles sont préremplies. Une date passée peut être renseignée pour refléter le départ réel.</p><form action={adoptReservation} className="mt-5 space-y-4"><input type="hidden" name="reservation_id" value={id} /><input type="hidden" name="return_to" value={returnTo} /><input type="hidden" name="client_command_id" value={randomUUID()} /><input type="hidden" name="expected_reservation_updated_at" value={row.updated_at ?? ""} /><label className="block text-sm font-semibold">Date et heure réelles<input required name="adoption_completed_at" type="datetime-local" defaultValue={localNow()} className="mt-2 w-full rounded-xl border bg-white px-3 py-2" /></label>{legacyExceptions.length ? <fieldset className="rounded-xl border border-amber-300 bg-amber-50 p-4"><legend className="px-1 text-sm font-semibold text-amber-950">Documents historiques à confirmer explicitement</legend>{legacyExceptions.map((code) => <label key={code} className="mt-3 flex items-start gap-3 text-sm"><input required type="checkbox" name="acknowledged_exception_code" value={code} /><span>{code.startsWith("commitment_certificate") ? "Le certificat d’engagement n’est pas signé dans le dossier." : "Le contrat de réservation n’est pas signé dans le dossier."}</span></label>)}<label className="mt-4 block text-sm font-semibold">Motif de l’exception<textarea required minLength={5} name="exception_reason" className="mt-2 min-h-24 w-full rounded-xl border bg-white px-3 py-2 font-normal" /></label></fieldset> : null}<label className="flex items-start gap-3 rounded-xl border bg-white p-4 text-sm font-medium"><input required type="checkbox" name="physical_documents_handed_over" value="confirmed" /><span>Carnet de santé et documents physiques remis à la famille.</span></label><button disabled={!ready} className="w-full rounded-xl bg-accent px-5 py-3 font-semibold text-white disabled:cursor-not-allowed disabled:bg-slate-200 disabled:text-slate-600">Confirmer le départ et finaliser l’adoption</button></form>{!ready ? <p className="mt-3 text-sm font-semibold text-amber-900">Complétez les preuves en attente avant de finaliser. Aucune dérogation n’est disponible.</p> : null}</section></main>;
}
